source/angular-ui-tree.css
Having font bold by default sounds like a bad idea to me.
=> removed font-weight: bold

README.md
It took me about 10 minutes to find out that I need to preset all nodes with items: [] so they could be nestable. I made this commit to save others that time :)
=> Update README.md - Added json structure

source/directives/uiTreeNode.js
Hey there... made another pull request for #314 . Last one was somehow broken and confusing.
=> Fixed 'exp' error when using Chrome and Angular-Batarang-Plugin #314

README.md, source/directives/uiTree.js, source/main.js, source/services/helper.js
It might be better to refactor the '$uiTreeHelper' factory as a provider, so it could be configured on the fly. Maybe I'll do it soon.
=> added rtl support

examples/views/basic-example.html, examples/views/connected-trees.html, examples/views/filter-nodes.html
as $uiTreeHelper service looks for the first one and it breaks the current examples.
=> Use data-nodrag instead of nodrag attribute in the examples

source/directives/uiTreeNode.js
Related issue #454
Related PR #470
=> Fix placeholder width

bower.json
=> fixed bower package name

README.md, source/controllers/nodeCtrl.spec.js
=> Add missing 'removed' callback to documentation

.travis.yml, README.md, e2e/basic-example/basic-example.js, e2e/basic-example/page.js, gulpfile.js, package.json, protractor.conf.js, tasks/protractor.js, tasks/scripts.js
Setup of E2E-tests using Protractor. With this PR I'd like to:
- add a Gulp command to execute the E2E-tests
- make sure E2E-tests are run by Travis
- provide minimal test-setup for the basic example page
=> Setup E2E-tests

package.json, source/controllers/nodeCtrl.js, source/controllers/nodeCtrl.spec.js
@Voles this is a fresh PR replacing https://github.com/angular-ui-tree/angular-ui-tree/pull/581.
=> #478 out of depth calculation

source/angular-ui-tree.css
=> #243 Update default styling to work with tables

source/directives/uiTreeNode.js
=> #611 Put drag element to the $rootElement instead of the body

index.js, package.json
=> Add support for browserify/webpack

e2e/basic-example/basic-example.js
just getting my feet wet. Assuming I'm not confused, I think this is merge-able. Looks like you had some variables names in there from some cut-paste example code maybe?
=> Change confusing variable name in e2e test

source/directives/uiTreeNode.js
where tree offset is wrong if scrolled horizontally.
Issue #323 in main repo
=> Firefox issue where tree offset is wrong if scrolled horizontally

examples/css/app.css, examples/index.html, examples/js/app.js, examples/js/table-example.js, examples/views/table-example.html
A demo of the implementation in #654 and #655
=> Added a demo using a table.

source/directives/uiTreeNode.js
This is a follow up on #607.
Edit: added [jsFiddle](http://jsfiddle.net/U3pVM/20264/)
=> Fix drop placeholder for tables

package.json
=> Remove duplicate license entry in package.json

source/directives/uiTreeNode.js
Implemented review feedback for PR #654.
=> Replace scope dependency when using the directive's element

README.md
Our team faced some difficulties with implementation and design, especially during the dragging state.
After some research we understood the mechanism behind the behavior of this awesome module, and we thought we could share it in case others might face similar issues.
=> Add information about styling to the README file

source/directives/uiTreeNode.js
=> Bind keydown handler to document

.jshintrc, e2e/basic-example/basic-example.js, e2e/basic-example/page.js
I put this together before seeing @jmcollin78's comment on https://github.com/angular-ui-tree/angular-ui-tree/pull/538.
In short, this code is gross, and should not be merged, but it does show a successful drag+drop e2e test with protractor. 
When I get a chance, I'll keep iterating on this, but any help or advice is much appreciated. Its been a few months since I was writing WebDriver stuff so I feel quite rusty. I'm also quite new to this OSS stuff, so please give me criticism if my etiquette is off or there is anything I can do to be better at this.
=> Drag & drop Protractor test - PoC

bower.json, dist/angular-ui-tree.css, gulpfile.js, tasks/styles.js
=> Include the CSS source files in the build

e2e/table-example/page.js, e2e/table-example/table-example.js
Here are a couple really basic e2e tests and a page object for the table-example.
=> create e2e tests for table-example

bower.json, package.json
I need to use this plugin with angular 1.5.  I've updated the bower deps to allow for angular 1.2-1.5.  The tests are all passing just fine in 1.5.  This is important to me because i'm packaging up an angular app as a runnable artifact on hub.docker.com
=> Angular 1.5

README.md, source/controllers/nodeCtrl.js, source/directives/uiTree.js
I needed some way to collapse/expanded some nodes when another node was collapsed/expanded. I added a callback on toggle that gives information about current node and its status.
=> Add callback after toggle

README.md, examples/js/expand-on-hover.js, examples/views/expand-on-hover.html
Documentation for #812. Updated README.md + the example page of the website.
=> Add documentation for the expand-on-hover feature

source/directives/uiTreeNode.js
Fixes issue https://github.com/angular-ui-tree/angular-ui-tree/issues/799
=> Fix cancelling drag behaviour when using the esc key

source/controllers/nodeCtrl.js, source/controllers/nodesCtrl.js, source/directives/uiTree.js, source/directives/uiTreeNode.js, source/services/helper.js
Don't call drag delay unless a delay is specified.  Also added comments so code is easier to follow.
=> Add performance improving code

source/directives/uiTreeNode.js, tasks/server.js
=> Fix moving nodes within the tree

source/directives/uiTreeNode.js, source/services/helper.js
Fix for issue #622.
I have removed checking for 'outOfBound' condition, because it was causing a problem when dragging an element outside of ui-tree.
=> Fix for issue 622 and prevent to remove placeholder if out of bound.

.travis.yml
Fix Firefox configuration. Credits to https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L23
=> Fix E2E-tests of the build

.travis.yml, package.json
Latest Node LTS release. See https://nodejs.org/en/blog/release/v6.9.0/
=> Update to Node 6

source/directives/uiTreeNode.js
As requested by @Voles in the discussion of PR #851, I have submitted a new PR with my proposed changes.
=> Expand-on-hover event not calling toggle callback function

source/angular-ui-tree.css, source/directives/uiTreeNode.js
With this pull request placeholder height calculating without margins, it looks much more beautiful.
=> Fixed placeholder height calculating

package.json
=> #906: Move postinstall hook to pretest
