angular-ui-tree/angular-ui-tree

source/controllers/treeCtrl.js

This should fix a bug that came up for me using the current distribution.  In my app, I am displaying a potentially huge tree, where each node has a lot of information associated with it, most of which is watched by Angular.  This causes incredible lag/freezing as Angular tries to process all of its watchers, so I'm creatively using `ng-switch` to only insert children into the DOM when necessary (upon expand).  My node template looks something like this:
```html
<div>{{lots of watched stuff}}</div>
<div ng-switch="collapsed">
<span ng-switch-when="false">
<ol ui-tree-nodes ng-model="node.children" ng-class="{'hidden': collapsed}">
<li ng-repeat="node in node.children" ui-tree-node data-collapsed="true" ng-include="'node-template.html'"></li>
</ol>
</span>
<span ng-switch-default></span> …
```

Handle null node in collapseOrExpand().

---

README.md

Without track by $index, people can get duplicate key error for unlimited nesting.
Link to the angular error page: http://bit.ly/1tRW15g

Bug fix to Duplicate Key in Repeater thrown by angular

---

bower.json

It's application developer reponsibility to add or not ES5-shim, based on targetted browser for his own application. 
So it should not be listed in dependencies, has it will always grab the dependency using build tools like wiredep.
Also, the main CSS file should be provided unminified, like JS file. (Still to be done)

bower.json fixes

---

README.md

Hi Jim, you may want to revert my pull request. I found out yesterday that your old way is correct. My patch will solve the duplicated key error but IT WILL CAUSE SEVERAL WEIRD BEHAVIORS. For instance, when you drag a node to somewhere,  the accepting parent node will not accept it correctly. So please do revert my pull request. 
Later I found out the duplicated key error for unlimited nesting originated from the new child node, which had the same hashKey as the parent node. Specifically, below is a short version of my newSubItem
$scope.newSubItem = function (scope) {
var nodeData = scope.$modelValue;
// this part copied the parent hashKey into child and was causing the problem
var childNode = JSON.parse(JSON.stringify(nodeData)); 
childNode.title = "blablah"; …

Revert "Bug fix to Duplicate Key in Repeater thrown by angular"

---

.gitattributes

I use Windows OS. And my git checkout *.js files with CRLF line endings. But JSCS requires LF line ending. For this reason, I could not build the project.
It is a fix for this problem.

Git should checkout JS files with LF line endings.

---

source/directives/uiTreeNode.js

keyup event was retaining scope which was retaining html nodes, cleaning up on $destroy
verified that this fixes memory leak
this article gave me insight into the problem:
http://www.codeproject.com/Articles/882966/Fixing-Memory-Leaks-in-AngularJS-and-other-JavaScr

Fixing severe memory leak

---

.jscsrc
source/controllers/handleCtrl.js
source/controllers/nodeCtrl.js
source/controllers/nodesCtrl.js
source/controllers/treeCtrl.js
source/directives/uiTree.js
source/directives/uiTreeHandle.js
source/directives/uiTreeNode.js
source/directives/uiTreeNodes.js
source/main.spec.js
source/services/helper.js
tasks/scripts.js

Add JSCS validation to enforce a predefined code style.

Setup JSCS configuration

---

source/controllers/treeCtrl.js
source/directives/uiTree.js
source/directives/uiTree.spec.js
source/directives/uiTreeNode.js
source/main.js

It seems that the functionality for toggling the empty placeholder is working correctly, but the documentation is incorrect. Because the property name is emptyPlaceHolderEnabled, the attribute should be `empty-place-holder-enabled`.
However, as `empty-placeholder-enabled` makes more sense, the API has been updated to reflect this.
Big thanks to @adambowen

Rename API attribute for toggling the empty placeholder

---

.gitignore
README.md
gulpfile.js
package.json
tasks/website.js

Simplify updating the website by adding the `$ gulp deploy` task to publish the updates.
The source of the website is based in the `/examples` directory.

Add deployment task for the website

---

README.md

- Adds clearer documentation for the `data-nodrop-enabled` attribute requested in #515.

[#515] Clarify nodrop-enabled documentation

---

source/directives/uiTreeNode.js
source/services/helper.js

In order to create some kind of trash can like behavior for two connected trees I need to evaluate the drag/move position in the dragStop event. On touch devices this doesn't work because most values of the pos-object are NaN or undefined. Please review the few changed lines of code in 'helper.js'.
Could these changes be merged into 2.8.0?

Fix position detection on touch devices when using jQuery

---

.jshintrc
source/directives/uiTree.js
source/directives/uiTree.spec.js

Ensure that the `uiTree` directive's `$nodesScope.$modelValue.length` watch returns a number. This fixes an issue where $nodeScope will sometimes become undefined if the underlying data structure is modified outside of angular-ui-tree. This would result in a `TypeError: Cannot read property '$modelValue' of
null`.

Fix crashing $nodesScope.$modelValue.length watch

---

source/directives/uiTreeNode.js

**Before**
`elements and pos variable was defining after the callback has been called.`
**After**
1. First setting the variables.
2. Call the dragStart callback.

Call the dragStart callback after setting up the variables

---

source/directives/uiTreeNode.js

Reset placeholder css display attribute, so it resets to whatever the placeholder class display attribute was set to.
In case someone is using a custom placeholder class this can unexpectedly change the css, for example when display is set to 'block-inline';
Pull request https://github.com/angular-ui-tree/angular-ui-tree/pull/525 added this behavior.

Reset placeholder display attribute instead of changing it to block

---

source/directives/uiTreeNode.js

test whether targetElm.scope() is defined to prevent Cannot read property '$type' of undefined" error

fix Cannot read property '$type' of undefined" error / issue #590

---

.gitignore
.travis.yml
karma.conf.js
package.json

Add test coverage details to the project using http://coveralls.io/
Thanks to @dsernst for writing http://dsernst.com/2015/09/02/node--mocha--travis--istanbul--coveralls-unit-tests--coverage-for-your-open-source-project/

Setup Coveralls integration

---

source/directives/uiTree.js

It attemps to find a tr element and use its children length as the td colspan. 
If it fails, it just sets a huge value to make sure the td takes the full width.
Edit: added [jsFiddle](http://jsfiddle.net/U3pVM/20265/)

Fix empty tree element for tables

---

dist/angular-ui-tree.js

Extra check for recursive call of the countSubTreeDepth

Cannot read property 'childNodes' of undefined

---

source/services/helper.js

Instead of again copying the original model value, use the already copied cloneModel that is exposed in the drag events. 
This way, users can intercept and change the cloned data.

Use this.sourceInfo.cloneModel  instead

---

source/directives/uiTree.js

The default accept() callback is only checked if nodropEnabled was set on
the dest scope, but not on the scope of the whole tree.
The examples and the doc both apply nodropEnabled to the ui-tree only.
This breaks the [clone example](https://angular-ui-tree.github.io/angular-ui-tree/#/cloning), if a node is selected from Tree 1, dragged over to Tree 2 (but not dropped), and then dragged back to Tree 1, a place holder will be shown for it.

Fix accept() to check $treeScope.nodropEnabled

---

README.md
source/directives/uiTreeNode.js
source/main.js

This changes the functionality of nodes so that whether they are collapsed or not by default is configurable. Currently, all nodes are expanded by default. This behavior cannot be changed, which can be limiting.
Because ```defaultCollapsed``` defaults to ```false```, behavior after this change should be consistent with the previous behavior.
```javascript
module.config(function(treeConfig) {
treeConfig.defaultCollapsed = true;
});
```

Feature: Ability to change whether nodes should be collapsed or expanded by default

---

README.md
source/directives/uiTreeNode.js

Fixes issue where *not* implementing beforeDrop in apps caused drop events to be rejected. This occurred because the event handler in ui-tree-node was checking for a truthy `allowDrop` value, however, if the callback was not implemented elsewhere, `allowDrop` was `undefined`, which is falsy and was being handled as a rejected drop.

Fix #680 (drag-drop not working if beforeDrop is not implemented)

---

source/directives/uiTreeNode.js

Dragging tree passed the bottom of page causes small amount of
whitespace to appear in Chrome

Fix whitespace at bottom of the page

---

source/directives/uiTreeNode.js

Enable setting a numeric value for the `expand-on-hover` attribute.
**Note:** This PR is created because of #810. The original author is @pkatta.

Enable setting a numeric value for the expand-on-hover attribute

---

README.md
source/directives/uiTreeNode.js
source/directives/uiTreeNode.spec.js

Fixes/is related to issues #49, #644, #158 and #544
Changes:
- New ui-tree-node attribute append-to allows for specifying any valid querySelector argument to scroll relative to the dragged node.
Example:
```
<div style="height: 300px; overflow:scroll;" class="wrapper"
ui-tree>
<ul style="height: 600px;" 
ui-tree-nodes>
<li ng-repeat="item in items"
ui-tree-node 
data-append-to="'.wrapper'">
</ul>
</div>
```

Allow DragElement to scroll any container

---

README.md
examples/index.html
examples/js/app.js
examples/js/append-child-on-hover.js
examples/views/append-child-on-hover.html
source/directives/uiTreeNode.js
source/main.js

This commit adds the ability to append a node as a child to another node via mouse-over. This is particularly useful for target nodes that have no children. The conventional way of adding nodes (dragging horizontally) remains unaffected.
The original code for this commit is based on @matthewboonstra's solution from #505. I edited it to allow moving a dragged node back to its original position after hovering over a preceding parent. I also restored broken horizontal mouse movement functionality and updated the original code based on changes to UiTreeHelper.
Tests with `gulp serve` on Windows 7 x64:
* Successfully executed 25 of 25 unit tests.
* Ran 6 specs, got 0 failures for the E2E-tests.

Add ability to append child nodes by dragging over parent

---

source/directives/uiTreeNode.js

Added isUiTreeRoot = false; in check if it or it's parents has a 'data-nodrag' attribute for preventing become item not selectable after clicking on this item.

Prevent node being non-collapsable after drag-and-drop in-place

---

source/controllers/nodesCtrl.js

**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Occasionally when moving a folder in a ui-tree, the safeApply method throws an error at: 
https://github.com/angular-ui-tree/angular-ui-tree/blob/bc2a301bb54d991542ec58e319fd47c007c25984/source/controllers/nodesCtrl.js#L52
error: Cannot read property $$phase of null
It would seem that this happens only occasionally because the $scope has already been destroyed when reaching this line. I have only been able to replicate this a very few times myself by just moving folders around waiting for the error to happen.
I was doing some research on $$phase and came across this comment:
https://stackoverflow.com/questions/22216441/what-is-the-difference-between-scope-root-and-rootscope#comment47424 …

Prefer $timeout over safeApply. 
